[package]
name = "bigint-buffer2-napi"
version = "1.0.0"
edition = "2021"
license = "MIT"
authors = ["Andrea Baccega <vekexasia@gmail.com>"]
description = "Node.js native bindings for BigInt/buffer conversion"

[lib]
crate-type = ["cdylib"]

[dependencies]
bigint-buffer2-core = { path = "../core" }
napi = { version = "2", default-features = false, features = ["napi6", "serde-json"] }
napi-derive = "2"

[build-dependencies]
napi-build = "2"

[profile.release]
lto = "fat"
opt-level = 3
codegen-units = 1
panic = "abort"
strip = true
