[package]
name = "bigint-buffer2-wasm"
version = "1.0.0"
edition = "2021"
license = "MIT"
authors = ["Andrea Baccega <vekexasia@gmail.com>"]
description = "WASM bindings for BigInt/buffer conversion"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bigint-buffer2-core = { path = "../core", default-features = false }
wasm-bindgen = "0.2"
js-sys = "0.3"

[profile.release]
opt-level = "s"
lto = true
